# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: John's Tech Blog
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the digital crossroads where curiosity meets expertise. I’m John, your navigator 
  through the labyrinthine world of technology. From the enchanting world of programming to the 
  robust foundations of architecture, the enigmatic pathways of networking, the sorcery of Linux 
  tricks, and the candid chapters of career wisdom—this blog is a tapestry of the snippets 
  I’ve unravelled in the techno-sphere.

  Whether you’re a seasoned tech aficionado or a novice with an appetite for knowledge, 
  I invite you to join me on a journey of discovery. Here, amidst the bytes and bits, 
  we’ll decode complex concepts and turn perplexity into prowess. So, gear up for an 
  adventure into the heart of all things tech – because, in this digital odyssey, 
  every byte counts!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jlandells.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jlandells
github_username:  jlandells

# Build settings
remote_theme: sighingnow/jekyll-gitbook
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
